[build]
public_url = "/"
dist = "dist"
pattern_script = '''
   <script type="module">import init, {main} from '{base}{js}'; await init('{base}{wasm}'); main(`{@appstate}`);</script>
'''
pattern_params = { "@appstate" = "appstate.json" }